# Generated by Django 3.2.12 on 2022-04-06 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre encargado')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido encargado')),
                ('mobile', models.CharField(max_length=10, verbose_name='Celular encargado')),
                ('note', models.CharField(max_length=200, verbose_name='Notas adicionales')),
            ],
            options={
                'db_table': 'cs_attendant',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Nombre de empresa')),
                ('ceo_name', models.CharField(max_length=100, verbose_name='Gerente')),
                ('cco_name', models.CharField(max_length=100, verbose_name='Jefe de compras')),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'cs_clients',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellidos')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('picture', models.CharField(max_length=250)),
                ('pricing', models.IntegerField(default=0)),
                ('last_modify', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'cs_products',
            },
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, verbose_name='Fijo corportativo')),
                ('mobile', models.CharField(max_length=10, verbose_name='Celular corporativo')),
                ('products', models.TextField(verbose_name='Lista de productos para esta sucursal')),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attendant')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
            options={
                'db_table': 'cs_venues',
            },
        ),
        migrations.CreateModel(
            name='StockByVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('Inventory', models.CharField(max_length=200)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.venues')),
            ],
            options={
                'db_table': 'cd_stock_by_venue',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('email', models.CharField(max_length=50, verbose_name='Correo electronico')),
                ('phone', models.CharField(max_length=32, verbose_name='Numero Telefonico')),
                ('mobile', models.CharField(max_length=32, verbose_name='Numero Telefonico alternativo')),
                ('profile_pic', models.CharField(max_length=250, null=True, verbose_name='Imagen de perfil')),
                ('position', models.CharField(max_length=150, verbose_name='Rol o cargo en la empresa')),
                ('birthday', models.DateField(blank=True, verbose_name='Fecha de cumpleaños')),
                ('country', models.CharField(max_length=32, verbose_name='País de origen')),
                ('city', models.CharField(max_length=32, verbose_name='Ciudad de residencia')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='Contador de inicios de sesión exitosos')),
                ('user', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de usuario')),
            ],
            options={
                'db_table': 'cs_users',
            },
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_date', models.DateField(default=django.utils.timezone.now)),
                ('deliver_date', models.DateField()),
                ('purchase_order', models.CharField(max_length=50)),
                ('order', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200, verbose_name='Notas adicionales')),
                ('status', models.CharField(default='No entregado', max_length=30)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.venues')),
            ],
            options={
                'db_table': 'cd_marketing',
            },
        ),
        migrations.AddField(
            model_name='attendant',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client'),
        ),
    ]
